version: '2.1'

jobs:
  test:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run:
          name: Run tests
          command: cargo test

workflows:
  version: 2
  test:
    jobs:
      - test
